version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
      - POSTGRES_DB=bank_trans
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgres://root:secret@postgres:5432/bank_trans?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432","--","/app/start.sh"] 
    command: ["/app/main"]   