# This is a basic workflow to help you get started with Actions

name: ci-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    name: Test
    runs-on: ubuntu-latest
    services:
        postgres:
          image: postgres:12
          env:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: root
            POSTGRES_DB: bank_trans
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:  
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Go 1.x
        uses: actions/checkout@v3 
        with:
          go-version: 1.15
        id: go

      - name: Print test
        run: echo Hello, world!

      - name: Install golang migrate
        run: |
            curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
            sudo mv migrate /usr/bin/
            which migrate
            
      - name: Migrate Uping...
        run: make migrateup

      - name: Test
        run:  make test